### ISSUE TITLE
undefined reference cv::findChessboardCornersSB

### ISSUE THREAD

**Issue by TiceCosmos** [twistedfall/opencv-rust#121]
When reporting an issue please state:
1. Debian GNU/Linux bullseye/sid x86_64
2. install by apt
3. version: 4.2.0
4. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```
    = note: /bin/ld: /tmp/test_opencv/target/debug/deps/libopencv-dcd3732e15cb71a5.rlib(calib3d.o): in function `cv::findChessboardCornersSB(cv::_InputArray const&, cv::Size_<int>, cv::_OutputArray const&, int)':

    $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.34.0/headers/4/opencv2/calib3d.hpp:1505: undefined reference to `cv::findChessboardCornersSB(cv::_InputArray const&, cv::Size_<int>, cv::_OutputArray const&, int, cv::_OutputArray const&)'

[test.zip](https://github.com/twistedfall/opencv-rust/files/4537384/test.zip)

--release no problem

**Comment by twistedfall** [comment]
That happens because of some changes in the OpenCV API between 4.2.0 and 4.3.0 and default crate binding have been regenerated for 4.3.0. So you need to enable `buildtime-bindgen` feature for it to work with 4.2.0.

**Comment by TiceCosmos** [comment]
> That happens because of some changes in the OpenCV API between 4.2.0 and 4.3.0 and default crate binding have been regenerated for 4.3.0. So you need to enable `buildtime-bindgen` feature for it to work with 4.2.0.

Thank you very much
