### ISSUE TITLE
Cannot build with opencv 4.5.0 with "contrib" feature

### ISSUE THREAD

**Issue by jerry73204** [twistedfall/opencv-rust#171]
I cannot build opencv-rust 0.46 with opencv 4.5.0 with "contrib" feature. It's fine for opencv 4.4.0. Here is the error message.

```
error[E0412]: cannot find type `Kinfu_Intr` in module `crate::rgbd`
    --> src/opencv/hub/rgbd.rs:1089:131
     |
1089 | ...ose: core::Matx44f, intrinsics: crate::rgbd::Kinfu_Intr) -> Result<()> {
     |                                                    ^^^^^^^^^^ not found in `crate::rgbd`

error[E0412]: cannot find type `Kinfu_Intr` in module `crate::rgbd`
    --> src/opencv/hub/rgbd.rs:1094:73
     |
1094 |     fn raycast(&self, camera_pose: core::Matx44f, intrinsics: crate::rgbd::Kinfu_Intr, frame_size: core::Size, points: &mut dyn core::ToOutp...
     |                                                                            ^^^^^^^^^^ not found in `crate::rgbd`

error[E0412]: cannot find type `Kinfu_Intr` in module `crate::rgbd`
    --> src/opencv/hub/sys.rs:4603:220
     |
4603 | ...:Matx44f, intrinsics: *const crate::rgbd::Kinfu_Intr) -> Result_void;
     |                                                    ^^^^^^^^^^ not found in `crate::rgbd`

error[E0412]: cannot find type `Kinfu_Intr` in module `crate::rgbd`
    --> src/opencv/hub/sys.rs:4604:204
     |
4604 | ...:Matx44f, intrinsics: *const crate::rgbd::Kinfu_Intr, frame_size: *const core::Size, points: *const c_void, normals: *const c_void) ->...
     |                                                    ^^^^^^^^^^ not found in `crate::rgbd`

error[E0308]: mismatched types
   --> src/opencv/hub/mcc.rs:127:88
    |
127 |         unsafe { sys::cv_mcc_CCheckerDetector_setNet_Net(self.as_raw_mut_CCheckerDetector(), net.opencv_as_extern()) }.into_result()
    |                                                                                              ^^^^^^^^^^^^^^^^^^^^^^ expected struct `Net`, found enum `libc::c_void`
    |
    = note: expected raw pointer `*const Net`
               found raw pointer `*const libc::c_void`

error: aborting due to 5 previous errors; 1 warning emitted

Some errors have detailed explanations: E0308, E0412.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `opencv`

To learn more, run the command again with --verbose.
```

**Comment by twistedfall** [comment]
Thanks, I’m already on it!

**Comment by twistedfall** [comment]
For now you can add "mcc" to the `ignore_modules` hashset in `make_modules` function in `build.rs`.

**Comment by jerry73204** [comment]
Thanks! That's a useful feature for me. Do you plan to make it accessible to Cargo features? Our work depends on your crate. Better if we need not to change the source code to take effect.

**Comment by twistedfall** [comment]
Well, first I plan to fix the generation of this new module :) But adding some way to configure module ignoring is a good idea, I'll see what can be done

**Comment by jerry73204** [comment]
Module ignoring has been my wanted feature since it reduces compile time, and avoids hassle of unmet dependencies.

I would prefer module whitelisting with most of which are enabled by default. To say a module is whitelisted, it is compiled whenever that opencv version has the module (or warning/panic is the module is not present). User chooses wanted modules and leaves remaining not compiled.

**Comment by twistedfall** [comment]
OpenCV 4.5.0 is now supported in v0.46.1 + you can adjust the set of generated modules by using `OPENCV_MODULE_BLACKLIST` and `OPENCV_MODULE_WHITELIST` environment variables (check readme for details).

**Comment by kahlil29** [comment]
I'm having a similar issue with `OpenCV 4.2.0` & `opencv-rust 0.43.2` (with `contrib` enabled)
 Is that expected? 
I initially tried with `OpenCV 4.5.0` and then found this issue so switched to `4.2.0` (what I was using initially). 
This removed the `Kinfu_Intr` errors but the last error, i.e. 

```
error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.43.3/src/opencv/hub/mcc.rs:127:88
    |
127 |         unsafe { sys::cv_mcc_CCheckerDetector_setNet_Net(self.as_raw_mut_CCheckerDetector(), net.opencv_as_extern()) }.into_result()
    |                                                                                              ^^^^^^^^^^^^^^^^^^^^^^ expected struct `opencv::hub::dnn::Net`, found enum `core::ffi::c_void`
    |
    = note: expected raw pointer `*const opencv::hub::dnn::Net`
               found raw pointer `*const core::ffi::c_void`

error: aborting due to previous error
``` 

Is not going away. 
Do I need to use a more recent version of the library? 

With `opencv-rust` `0.46.1` I get a whole lot of `strip_prefix` errors thrown by the `binding_generator` 
like 
```
 --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-binding-generator-0.21.2/src/comment.rs:26:39
   |
26 |             if let Some(new_line) = line_clean.strip_prefix(MULTILINE_PREFIX) {
   |                                                ^^^^^^^^^^^^
   |
   = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information
```

**Comment by kahlil29** [comment]
Okay I checked the issue it's referring to and it seems like that has been fixed so do I then need to upgrade my `rustc` version to get this to work? 
It's currently : `rustc 1.44.1`

**Comment by kahlil29** [comment]
Okay updating to `rustc 1.47.0` solved the issue 👍
